language: python
python:
  - "2.7"
  - "3.6"
  - "3.8"
install:
  - pip install -r requirements.txt
script:
  - python -m pytest
notifications:
  email:
    recipients:
      - sgaladha@ncsu.edu
      - sdamulu@ncsu.edu
      - cmandap@ncsu.edu
      - nrlavani@ncsu.edu
      - hbharat@ncsu.edu

    on_success: never
    on_failure: always